
services:
  - type: web
    name: arabian-coast-app
    env: node
    plan: free
    buildCommand: npm ci && npm install --production=false && node build-render.js
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: arabian-coast-db
          property: connectionString

databases:
  - name: arabian-coast-db
    databaseName: arabian_coast
    user: arabian_coast_user
    plan: free
