services:
  - type: web
    name: arabian-coast-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: arabian-coast-db
          property: connectionString

databases:
  - name: arabian-coast-db
    databaseName: arabian_coast
    user: arabian_coast_user
    plan: free